//! Generate the Go and TypeScript event vocabulary from the pipeline contract.
//!
//! The Rust types are the source of truth, `contracts/pipeline.json` is their
//! projection (decision (c), `notes/DESIGN_STAGE_SDK.md`), and these ports are
//! a projection of that same document — so a stage author in Go or TypeScript
//! gets typed events without anyone hand-maintaining a second catalog.
//!
//! What this deliberately does NOT emit: the framing. `Reader`/`Writer` are
//! hand-written in each SDK because framing is behavior, not shape, and the
//! conformance harness already gates them byte-for-byte against the Rust
//! writer. This file is types and constants only.
//!
//! Regenerated by the `emit-stage-sdk` binary, gated by
//! `just check-stage-sdk-gen`. Hand-editing the output is always wrong.

use std::collections::BTreeMap;

use serde_json::Value;

const HEADER: &str = "\
// AUTO-GENERATED by emit-stage-sdk — do not edit.
// Run: just gen-stage-sdk
//
// The BranchKit pipeline event vocabulary, projected from
// contracts/pipeline.json (itself generated from the branchkit-stage-sdk Rust
// types). Framing lives in the hand-written reader/writer alongside this file.
";

/// `audio_chunk` → `AudioChunk`.
fn pascal(s: &str) -> String {
    s.split(['_', '.'])
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// Doc comment text for a field or type, if the schema carries one. Rust doc
/// comments arrive here with newlines; each target flattens them its own way.
fn description(schema: &Value) -> Option<&str> {
    schema.get("description").and_then(Value::as_str)
}

/// A `$ref` into `components/schemas`, if this is one.
fn ref_name(schema: &Value) -> Option<&str> {
    schema
        .get("$ref")
        .and_then(Value::as_str)
        .and_then(|r| r.rsplit('/').next())
}

/// Is this schema nullable — `"type": ["number", "null"]`?
fn is_nullable(schema: &Value) -> bool {
    schema
        .get("type")
        .and_then(Value::as_array)
        .is_some_and(|types| types.iter().any(|t| t == "null"))
}

/// The non-null half of a type, whether scalar or nullable union.
fn base_type(schema: &Value) -> Option<&str> {
    match schema.get("type") {
        Some(Value::String(s)) => Some(s.as_str()),
        Some(Value::Array(types)) => types
            .iter()
            .filter_map(Value::as_str)
            .find(|t| *t != "null"),
        _ => None,
    }
}

/// A schema of literal `true` (or an untyped object) accepts anything.
fn is_any(schema: &Value) -> bool {
    schema == &Value::Bool(true) || (schema.get("type").is_none() && ref_name(schema).is_none())
}

fn go_scalar(schema: &Value, base: &str) -> String {
    let format = schema.get("format").and_then(Value::as_str).unwrap_or("");
    match (base, format) {
        ("string", _) => "string".into(),
        ("boolean", _) => "bool".into(),
        ("integer", "uint64") => "uint64".into(),
        ("integer", "uint32") => "uint32".into(),
        ("integer", "uint") => "uint".into(),
        ("integer", "int64") => "int64".into(),
        ("integer", "int32") => "int32".into(),
        ("integer", _) => "int".into(),
        ("number", "float") => "float32".into(),
        ("number", _) => "float64".into(),
        _ => "json.RawMessage".into(),
    }
}

fn go_type(schema: &Value) -> String {
    if is_any(schema) {
        return "json.RawMessage".into();
    }
    if let Some(name) = ref_name(schema) {
        return name.to_string();
    }
    match base_type(schema) {
        Some("array") => {
            let items = schema.get("items").unwrap_or(&Value::Bool(true));
            format!("[]{}", go_type(items))
        }
        Some("object") => {
            // `additionalProperties: true` is an open map; a typed one keeps
            // its value type.
            match schema.get("additionalProperties") {
                Some(Value::Bool(true)) | None => "map[string]any".into(),
                Some(v) => format!("map[string]{}", go_type(v)),
            }
        }
        Some(base) => go_scalar(schema, base),
        None => "json.RawMessage".into(),
    }
}

fn ts_type(schema: &Value) -> String {
    if is_any(schema) {
        return "unknown".into();
    }
    if let Some(name) = ref_name(schema) {
        return name.to_string();
    }
    match base_type(schema) {
        Some("array") => {
            let items = schema.get("items").unwrap_or(&Value::Bool(true));
            let inner = ts_type(items);
            // Keep unions readable: `(A | B)[]` rather than `A | B[]`.
            if inner.contains('|') {
                format!("({inner})[]")
            } else {
                format!("{inner}[]")
            }
        }
        Some("object") => match schema.get("additionalProperties") {
            Some(Value::Bool(true)) | None => "Record<string, unknown>".into(),
            Some(v) => format!("Record<string, {}>", ts_type(v)),
        },
        Some("string") => "string".into(),
        Some("boolean") => "boolean".into(),
        Some("integer") | Some("number") => "number".into(),
        _ => "unknown".into(),
    }
}

/// Sorted `(name, schema)` pairs from `components.schemas`.
fn schemas(doc: &Value) -> BTreeMap<&str, &Value> {
    doc.get("components")
        .and_then(|c| c.get("schemas"))
        .and_then(Value::as_object)
        .map(|m| m.iter().map(|(k, v)| (k.as_str(), v)).collect())
        .unwrap_or_default()
}

/// Sorted wire tags from `eventTypes`.
fn event_tags(doc: &Value) -> Vec<&str> {
    let mut tags: Vec<&str> = doc
        .get("eventTypes")
        .and_then(Value::as_object)
        .map(|m| m.keys().map(String::as_str).collect())
        .unwrap_or_default();
    tags.sort_unstable();
    tags
}

/// Fields of an object schema as `(json_name, schema, required)`, sorted.
fn fields(schema: &Value) -> Vec<(&str, &Value, bool)> {
    let required: Vec<&str> = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|a| a.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    let mut out: Vec<(&str, &Value, bool)> = schema
        .get("properties")
        .and_then(Value::as_object)
        .map(|m| {
            m.iter()
                .map(|(k, v)| {
                    (
                        k.as_str(),
                        v,
                        required.contains(&k.as_str()) && !is_nullable(v),
                    )
                })
                .collect()
        })
        .unwrap_or_default();
    out.sort_by_key(|(name, _, _)| *name);
    out
}

/// Flatten a Rust doc comment into `prefix`-led lines.
fn doc_lines(text: &str, prefix: &str, indent: &str) -> String {
    text.lines()
        .map(|l| {
            format!("{indent}{prefix} {}", l.trim_end())
                .trim_end()
                .to_string()
        })
        .collect::<Vec<_>>()
        .join("\n")
        + "\n"
}

pub fn go_source(doc: &Value) -> String {
    let mut out = String::from(HEADER);
    out.push_str("\npackage pipeline\n\nimport (\n\t\"encoding/json\"\n\t\"strings\"\n)\n\n");
    out.push_str(
        "// Ensure the json import is used even if no type needs it.\nvar _ json.RawMessage\n\n",
    );

    out.push_str("// Wire event tags. Use these instead of string literals so vocabulary\n// drift is a compile error.\nconst (\n");
    for tag in event_tags(doc) {
        out.push_str(&format!("\tEvent{} = \"{tag}\"\n", pascal(tag)));
    }
    out.push_str(")\n\n");

    out.push_str(&format!(
        "// ExtEventPrefix reserves the open namespace a stage emits custom events\n\
         // under: at least three non-empty dot segments, `ext.<vendor>.<name>`.\n\
         const ExtEventPrefix = {:?}\n\n\
         // IsValidExtEventType reports whether a custom event type is well-formed.\n\
         func IsValidExtEventType(t string) bool {{\n\
         \tif !strings.HasPrefix(t, ExtEventPrefix) {{\n\
         \t\treturn false\n\
         \t}}\n\
         \tparts := strings.Split(t, \".\")\n\
         \tif len(parts) < 3 {{\n\
         \t\treturn false\n\
         \t}}\n\
         \tfor _, p := range parts {{\n\
         \t\tif p == \"\" {{\n\
         \t\t\treturn false\n\
         \t\t}}\n\
         \t}}\n\
         \treturn true\n\
         }}\n\n\
         // Environment variables the platform sets when it spawns a stage.\n\
         // NEVER re-derive these paths: the sandbox grants access by the path the\n\
         // platform computed, so a second spelling is a denial that reads like a\n\
         // missing directory.\n\
         const (\n\
         \tModelsDirEnv = {:?}\n\
         \tDataDirEnv   = {:?}\n\
         )\n\n",
        crate::events::EXT_EVENT_PREFIX,
        crate::MODELS_DIR_ENV,
        crate::DATA_DIR_ENV,
    ));

    for (name, schema) in schemas(doc) {
        if let Some(d) = description(schema) {
            out.push_str(&doc_lines(d, "//", ""));
        }
        out.push_str(&format!("type {name} struct {{\n"));
        for (fname, fschema, required) in fields(schema) {
            if let Some(d) = description(fschema) {
                out.push_str(&doc_lines(d, "//", "\t"));
            }
            let base = go_type(fschema);
            // Pointer + omitempty for anything the wire may leave out; slices
            // and maps are already nil-able, and RawMessage is a slice.
            let pointerish =
                base.starts_with("[]") || base.starts_with("map[") || base == "json.RawMessage";
            let ty = if required || pointerish {
                base.clone()
            } else {
                format!("*{base}")
            };
            let tag = if required {
                format!("`json:\"{fname}\"`")
            } else {
                format!("`json:\"{fname},omitempty\"`")
            };
            out.push_str(&format!("\t{} {ty} {tag}\n", pascal(fname)));
        }
        out.push_str("}\n\n");
    }
    out
}

pub fn ts_source(doc: &Value) -> String {
    let mut out = String::from(HEADER);
    out.push('\n');

    out.push_str("/** Wire event tags. Use instead of string literals so vocabulary drift is a type error. */\n");
    for tag in event_tags(doc) {
        out.push_str(&format!(
            "export const Event{} = \"{tag}\" as const;\n",
            pascal(tag)
        ));
    }
    out.push('\n');

    out.push_str(&format!(
        "/**\n * The open namespace a stage emits custom events under: at least three\n\
         \x20* non-empty dot segments, `ext.<vendor>.<name>`.\n */\n\
         export const EXT_EVENT_PREFIX = {:?} as const;\n\n\
         /** Is this custom event type well-formed? */\n\
         export function isValidExtEventType(t: string): boolean {{\n\
         \x20 if (!t.startsWith(EXT_EVENT_PREFIX)) return false;\n\
         \x20 const parts = t.split(\".\");\n\
         \x20 return parts.length >= 3 && parts.every((p) => p.length > 0);\n\
         }}\n\n\
         /**\n\
         \x20* Environment variables the platform sets when it spawns a stage.\n\
         \x20* NEVER re-derive these paths: the sandbox grants access by the path the\n\
         \x20* platform computed, so a second spelling is a denial that reads like a\n\
         \x20* missing directory.\n\
         \x20*/\n\
         export const MODELS_DIR_ENV = {:?} as const;\n\
         export const DATA_DIR_ENV = {:?} as const;\n\n",
        crate::events::EXT_EVENT_PREFIX,
        crate::MODELS_DIR_ENV,
        crate::DATA_DIR_ENV,
    ));

    for (name, schema) in schemas(doc) {
        if let Some(d) = description(schema) {
            out.push_str("/**\n");
            out.push_str(&doc_lines(d, " *", ""));
            out.push_str(" */\n");
        }
        out.push_str(&format!("export interface {name} {{\n"));
        for (fname, fschema, required) in fields(schema) {
            if let Some(d) = description(fschema) {
                out.push_str("  /**\n");
                out.push_str(&doc_lines(d, "   *", ""));
                out.push_str("   */\n");
            }
            let opt = if required { "" } else { "?" };
            out.push_str(&format!("  {fname}{opt}: {};\n", ts_type(fschema)));
        }
        out.push_str("}\n\n");
    }
    out
}
