//! Generate the Go and TypeScript event vocabulary from the pipeline contract.
//!
//! The Rust types are the source of truth, `contracts/pipeline.json` is their
//! projection (decision (c), `notes/DESIGN_STAGE_SDK.md`), and these ports are
//! a projection of that same document — so a stage author in Go or TypeScript
//! gets typed events without anyone hand-maintaining a second catalog.
//!
//! What this deliberately does NOT emit: the framing. `Reader`/`Writer` are
//! hand-written in each SDK because framing is behavior, not shape, and the
//! conformance harness already gates them byte-for-byte against the Rust
//! writer. This file is types and constants only.
//!
//! Regenerated by the `emit-stage-sdk` binary, gated by
//! `just check-stage-sdk-gen`. Hand-editing the output is always wrong.

use std::collections::BTreeMap;

use serde_json::Value;

/// Which slice of the vocabulary a type or tag belongs to.
///
/// This is the SDK-surface half of decision (v) — the platform decodes an
/// event only when it must read the contents to do its own job — projected
/// into what an author has to import. The point is that the DEFAULT import is
/// domain-free: someone writing a foot pedal or a frame source should never be
/// handed a command-grammar DAG and left to work out that it is irrelevant to
/// them.
///
/// Tiers form a DAG with exactly one edge: `Core` → `Audio`, because
/// `Capability` carries `audio_formats` and the runtime's consumer interface
/// and stop-request both name audio session types. That edge is a real finding
/// rather than a packaging artifact — the transport tier is not yet fully
/// domain-free, and the valve note records it. `Recognition` and `Monitors`
/// depend on nothing and are depended on by nothing, which is exactly what
/// makes them opt-in.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Tier {
    /// Transport: what every stage speaks regardless of domain.
    Core,
    /// The audio session vocabulary.
    Audio,
    /// Recognition: transcripts, the word union, the command-grammar DAG.
    Recognition,
    /// First-party monitor families (device, display, location, power).
    ///
    /// These are typed for a weaker reason than the rest — the platform decodes
    /// them only to rename them onto the bus as `_platform.*`. Legacy-typed,
    /// not exemplary: a third-party monitor today would use `ext.<vendor>.*`.
    Monitors,
}

impl Tier {
    pub const ALL: &'static [Tier] = &[Tier::Core, Tier::Audio, Tier::Recognition, Tier::Monitors];

    /// Go sub-package / TS sub-module name. `None` = the root.
    pub fn module(self) -> Option<&'static str> {
        match self {
            Tier::Core => None,
            Tier::Audio => Some("audio"),
            Tier::Recognition => Some("recognition"),
            Tier::Monitors => Some("monitors"),
        }
    }

    fn blurb(self) -> &'static str {
        match self {
            Tier::Core => "Transport vocabulary: the handshake, framing, error and flow-credit\n// types every stage speaks whatever its domain.",
            Tier::Audio => "The audio session vocabulary. Import this if your stage produces or\n// consumes an audio stream.",
            Tier::Recognition => "Recognition vocabulary: transcripts, the word union, and the\n// command-grammar DAG a recognizer decodes against. Import this only if\n// you are building a speech recognizer or an STT stage.",
            Tier::Monitors => "First-party monitor families. Typed because the platform renames them\n// onto its bus as `_platform.*` events; a third-party monitor uses\n// `ext.<vendor>.*` instead and needs nothing from here.",
        }
    }
}

/// The tier a generated type belongs to.
pub fn tier_of_type(name: &str) -> Tier {
    match name {
        "WireHeader" | "Capability" | "ErrorEvent" | "FlowCredit" => Tier::Core,
        "AudioStart" | "AudioChunk" | "AudioStop" | "AudioFormat" => Tier::Audio,
        "Transcript" | "VocabularyUpdate" | "GrammarDagWire" | "WireArc" | "OpenState" => {
            Tier::Recognition
        }
        _ => Tier::Monitors,
    }
}

/// The tier a wire tag belongs to.
pub fn tier_of_tag(tag: &str) -> Tier {
    match tag {
        "capability" | "error" | "flow_credit" => Tier::Core,
        "audio_start" | "audio_chunk" | "audio_stop" => Tier::Audio,
        "transcript" | "vocabulary_update" => Tier::Recognition,
        _ => Tier::Monitors,
    }
}

const HEADER: &str = "\
// AUTO-GENERATED by emit-stage-sdk — do not edit.
// Run: just gen-stage-sdk
//
// The BranchKit pipeline event vocabulary, projected from
// contracts/pipeline.json (itself generated from the branchkit-stage-sdk Rust
// types). Framing lives in the hand-written reader/writer alongside this file.
";

/// `audio_chunk` → `AudioChunk`.
fn pascal(s: &str) -> String {
    s.split(['_', '.'])
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// Doc comment text for a field or type, if the schema carries one. Rust doc
/// comments arrive here with newlines; each target flattens them its own way.
fn description(schema: &Value) -> Option<&str> {
    schema.get("description").and_then(Value::as_str)
}

/// A `$ref` into `components/schemas`, if this is one.
fn ref_name(schema: &Value) -> Option<&str> {
    schema
        .get("$ref")
        .and_then(Value::as_str)
        .and_then(|r| r.rsplit('/').next())
}

/// Is this schema nullable — `"type": ["number", "null"]`?
fn is_nullable(schema: &Value) -> bool {
    schema
        .get("type")
        .and_then(Value::as_array)
        .is_some_and(|types| types.iter().any(|t| t == "null"))
}

/// The non-null half of a type, whether scalar or nullable union.
fn base_type(schema: &Value) -> Option<&str> {
    match schema.get("type") {
        Some(Value::String(s)) => Some(s.as_str()),
        Some(Value::Array(types)) => types
            .iter()
            .filter_map(Value::as_str)
            .find(|t| *t != "null"),
        _ => None,
    }
}

/// A schema of literal `true` (or an untyped object) accepts anything.
fn is_any(schema: &Value) -> bool {
    schema == &Value::Bool(true) || (schema.get("type").is_none() && ref_name(schema).is_none())
}

/// Go import path of the root package, for qualifying cross-tier references.
const GO_ROOT_PKG: &str = "github.com/branchkit/plugin-sdk-go/pipeline";

fn go_scalar(schema: &Value, base: &str) -> String {
    let format = schema.get("format").and_then(Value::as_str).unwrap_or("");
    match (base, format) {
        ("string", _) => "string".into(),
        ("boolean", _) => "bool".into(),
        ("integer", "uint64") => "uint64".into(),
        ("integer", "uint32") => "uint32".into(),
        ("integer", "uint") => "uint".into(),
        ("integer", "int64") => "int64".into(),
        ("integer", "int32") => "int32".into(),
        ("integer", _) => "int".into(),
        ("number", "float") => "float32".into(),
        ("number", _) => "float64".into(),
        _ => "json.RawMessage".into(),
    }
}

/// Qualify a referenced type when it lives in a different tier. Only the
/// audio tier does this today (for `AudioFormat`), but the rule is general so
/// a future family cannot silently produce an unresolvable name.
fn qualify(name: &str, from: Tier) -> String {
    let owner = tier_of_type(name);
    if owner == from {
        return name.to_string();
    }
    match owner.module() {
        None => format!("pipeline.{name}"),
        Some(m) => format!("{m}.{name}"),
    }
}

fn go_type(schema: &Value, tier: Tier) -> String {
    if is_any(schema) {
        return "json.RawMessage".into();
    }
    if let Some(name) = ref_name(schema) {
        return qualify(name, tier);
    }
    match base_type(schema) {
        Some("array") => {
            let items = schema.get("items").unwrap_or(&Value::Bool(true));
            format!("[]{}", go_type(items, tier))
        }
        Some("object") => match schema.get("additionalProperties") {
            Some(Value::Bool(true)) | None => "map[string]any".into(),
            Some(v) => format!("map[string]{}", go_type(v, tier)),
        },
        Some(base) => go_scalar(schema, base),
        None => "json.RawMessage".into(),
    }
}

fn ts_type(schema: &Value, tier: Tier) -> String {
    if is_any(schema) {
        return "unknown".into();
    }
    if let Some(name) = ref_name(schema) {
        // TS imports the name directly, so no qualification — only the import
        // list differs per tier.
        let _ = tier;
        return name.to_string();
    }
    match base_type(schema) {
        Some("array") => {
            let items = schema.get("items").unwrap_or(&Value::Bool(true));
            let inner = ts_type(items, tier);
            if inner.contains('|') {
                format!("({inner})[]")
            } else {
                format!("{inner}[]")
            }
        }
        Some("object") => match schema.get("additionalProperties") {
            Some(Value::Bool(true)) | None => "Record<string, unknown>".into(),
            Some(v) => format!("Record<string, {}>", ts_type(v, tier)),
        },
        Some("string") => "string".into(),
        Some("boolean") => "boolean".into(),
        Some("integer") | Some("number") => "number".into(),
        _ => "unknown".into(),
    }
}

/// Sorted `(name, schema)` pairs from `components.schemas`.
fn schemas(doc: &Value) -> BTreeMap<&str, &Value> {
    doc.get("components")
        .and_then(|c| c.get("schemas"))
        .and_then(Value::as_object)
        .map(|m| m.iter().map(|(k, v)| (k.as_str(), v)).collect())
        .unwrap_or_default()
}

/// Sorted wire tags from `eventTypes`.
fn event_tags(doc: &Value) -> Vec<&str> {
    let mut tags: Vec<&str> = doc
        .get("eventTypes")
        .and_then(Value::as_object)
        .map(|m| m.keys().map(String::as_str).collect())
        .unwrap_or_default();
    tags.sort_unstable();
    tags
}

/// Fields of an object schema as `(json_name, schema, required)`, sorted.
fn fields(schema: &Value) -> Vec<(&str, &Value, bool)> {
    let required: Vec<&str> = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|a| a.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    let mut out: Vec<(&str, &Value, bool)> = schema
        .get("properties")
        .and_then(Value::as_object)
        .map(|m| {
            m.iter()
                .map(|(k, v)| {
                    (
                        k.as_str(),
                        v,
                        required.contains(&k.as_str()) && !is_nullable(v),
                    )
                })
                .collect()
        })
        .unwrap_or_default();
    out.sort_by_key(|(name, _, _)| *name);
    out
}

/// Flatten a Rust doc comment into `prefix`-led lines.
fn doc_lines(text: &str, prefix: &str, indent: &str) -> String {
    text.lines()
        .map(|l| {
            format!("{indent}{prefix} {}", l.trim_end())
                .trim_end()
                .to_string()
        })
        .collect::<Vec<_>>()
        .join("\n")
        + "\n"
}

/// Names this tier references from other tiers, sorted and deduped.
fn cross_tier_refs(doc: &Value, tier: Tier) -> Vec<(&'static str, String)> {
    let mut out: Vec<(&'static str, String)> = Vec::new();
    for (name, schema) in schemas(doc) {
        if tier_of_type(name) != tier {
            continue;
        }
        for (_, fschema, _) in fields(schema) {
            collect_refs(fschema, tier, &mut out);
        }
    }
    out.sort();
    out.dedup();
    out
}

fn collect_refs(schema: &Value, tier: Tier, acc: &mut Vec<(&'static str, String)>) {
    if let Some(name) = ref_name(schema) {
        let owner = tier_of_type(name);
        if owner != tier {
            let module = owner.module().unwrap_or("pipeline");
            acc.push((module, name.to_string()));
        }
        return;
    }
    if let Some(items) = schema.get("items") {
        collect_refs(items, tier, acc);
    }
    if let Some(Value::Object(_)) = schema.get("additionalProperties") {
        collect_refs(&schema["additionalProperties"], tier, acc);
    }
}

pub fn go_source(doc: &Value, tier: Tier) -> String {
    let mut out = String::from(HEADER);
    out.push_str(&format!("//\n// {}\n", tier.blurb()));
    let pkg = tier.module().unwrap_or("pipeline");
    out.push_str(&format!("\npackage {pkg}\n\n"));

    let cross = cross_tier_refs(doc, tier);
    let mut modules: Vec<&str> = cross.iter().map(|(m, _)| *m).collect();
    modules.sort_unstable();
    modules.dedup();
    out.push_str("import (\n\t\"encoding/json\"\n");
    if tier == Tier::Core {
        out.push_str("\t\"strings\"\n");
    }
    if !modules.is_empty() {
        out.push('\n');
        for m in &modules {
            if *m == "pipeline" {
                out.push_str(&format!("\t\"{GO_ROOT_PKG}\"\n"));
            } else {
                out.push_str(&format!("\t\"{GO_ROOT_PKG}/{m}\"\n"));
            }
        }
    }
    out.push_str(")\n\n");
    out.push_str(
        "// Ensure the json import is used even if no type needs it.\nvar _ json.RawMessage\n\n",
    );

    let tags: Vec<&str> = event_tags(doc)
        .into_iter()
        .filter(|t| tier_of_tag(t) == tier)
        .collect();
    if !tags.is_empty() {
        out.push_str("// Wire event tags. Use these instead of string literals so vocabulary\n// drift is a compile error.\nconst (\n");
        for tag in tags {
            out.push_str(&format!("\tEvent{} = \"{tag}\"\n", pascal(tag)));
        }
        out.push_str(")\n\n");
    }

    if tier == Tier::Core {
        out.push_str(&format!(
            "// ExtEventPrefix reserves the open namespace a stage emits custom events\n\
             // under: at least three non-empty dot segments, `ext.<vendor>.<name>`.\n\
             //\n\
             // This is the namespace EVERY domain the platform does not itself decode\n\
             // lives in — a foot pedal, a frame source, a MIDI filter. It needs no\n\
             // platform change and no entry in any catalog.\n\
             const ExtEventPrefix = {:?}\n\n\
             // IsValidExtEventType reports whether a custom event type is well-formed.\n\
             func IsValidExtEventType(t string) bool {{\n\
             \tif !strings.HasPrefix(t, ExtEventPrefix) {{\n\
             \t\treturn false\n\
             \t}}\n\
             \tparts := strings.Split(t, \".\")\n\
             \tif len(parts) < 3 {{\n\
             \t\treturn false\n\
             \t}}\n\
             \tfor _, p := range parts {{\n\
             \t\tif p == \"\" {{\n\
             \t\t\treturn false\n\
             \t\t}}\n\
             \t}}\n\
             \treturn true\n\
             }}\n\n\
             // Environment variables the platform sets when it spawns a stage.\n\
             // NEVER re-derive these paths: the sandbox grants access by the path the\n\
             // platform computed, so a second spelling is a denial that reads like a\n\
             // missing directory.\n\
             const (\n\
             \tModelsDirEnv = {:?}\n\
             \tDataDirEnv   = {:?}\n\
             )\n\n",
            crate::events::EXT_EVENT_PREFIX,
            crate::MODELS_DIR_ENV,
            crate::DATA_DIR_ENV,
        ));
    }

    for (name, schema) in schemas(doc) {
        if tier_of_type(name) != tier {
            continue;
        }
        if let Some(d) = description(schema) {
            out.push_str(&doc_lines(d, "//", ""));
        }
        out.push_str(&format!("type {name} struct {{\n"));
        for (fname, fschema, required) in fields(schema) {
            if let Some(d) = description(fschema) {
                out.push_str(&doc_lines(d, "//", "\t"));
            }
            let base = go_type(fschema, tier);
            let pointerish =
                base.starts_with("[]") || base.starts_with("map[") || base == "json.RawMessage";
            let ty = if required || pointerish {
                base.clone()
            } else {
                format!("*{base}")
            };
            let tag = if required {
                format!("`json:\"{fname}\"`")
            } else {
                format!("`json:\"{fname},omitempty\"`")
            };
            out.push_str(&format!("\t{} {ty} {tag}\n", pascal(fname)));
        }
        out.push_str("}\n\n");
    }
    out
}

pub fn ts_source(doc: &Value, tier: Tier) -> String {
    let mut out = String::from(HEADER);
    out.push_str(&format!(
        "//\n// {}\n\n",
        tier.blurb().replace("\n// ", "\n// ")
    ));

    let cross = cross_tier_refs(doc, tier);
    if !cross.is_empty() {
        let mut by_module: BTreeMap<&str, Vec<String>> = BTreeMap::new();
        for (m, name) in &cross {
            by_module.entry(m).or_default().push(name.clone());
        }
        for (module, mut names) in by_module {
            names.sort();
            names.dedup();
            let file = if module == "pipeline" {
                "./pipeline_events_gen.js".to_string()
            } else {
                format!("./pipeline_events_{module}_gen.js")
            };
            out.push_str(&format!(
                "import type {{ {} }} from \"{file}\";\n",
                names.join(", ")
            ));
            out.push_str(&format!("export type {{ {} }};\n\n", names.join(", ")));
        }
    }

    let tags: Vec<&str> = event_tags(doc)
        .into_iter()
        .filter(|t| tier_of_tag(t) == tier)
        .collect();
    if !tags.is_empty() {
        out.push_str("/** Wire event tags. Use instead of string literals so vocabulary drift is a type error. */\n");
        for tag in tags {
            out.push_str(&format!(
                "export const Event{} = \"{tag}\" as const;\n",
                pascal(tag)
            ));
        }
        out.push('\n');
    }

    if tier == Tier::Core {
        out.push_str(&format!(
            "/**\n * The open namespace a stage emits custom events under: at least three\n\
             \x20* non-empty dot segments, `ext.<vendor>.<name>`.\n\
             \x20*\n\
             \x20* This is the namespace EVERY domain the platform does not itself decode\n\
             \x20* lives in — a foot pedal, a frame source, a MIDI filter. It needs no\n\
             \x20* platform change and no entry in any catalog.\n */\n\
             export const EXT_EVENT_PREFIX = {:?} as const;\n\n\
             /** Is this custom event type well-formed? */\n\
             export function isValidExtEventType(t: string): boolean {{\n\
             \x20 if (!t.startsWith(EXT_EVENT_PREFIX)) return false;\n\
             \x20 const parts = t.split(\".\");\n\
             \x20 return parts.length >= 3 && parts.every((p) => p.length > 0);\n\
             }}\n\n\
             /**\n\
             \x20* Environment variables the platform sets when it spawns a stage.\n\
             \x20* NEVER re-derive these paths: the sandbox grants access by the path the\n\
             \x20* platform computed, so a second spelling is a denial that reads like a\n\
             \x20* missing directory.\n\
             \x20*/\n\
             export const MODELS_DIR_ENV = {:?} as const;\n\
             export const DATA_DIR_ENV = {:?} as const;\n\n",
            crate::events::EXT_EVENT_PREFIX,
            crate::MODELS_DIR_ENV,
            crate::DATA_DIR_ENV,
        ));
    }

    for (name, schema) in schemas(doc) {
        if tier_of_type(name) != tier {
            continue;
        }
        if let Some(d) = description(schema) {
            out.push_str("/**\n");
            out.push_str(&doc_lines(d, " *", ""));
            out.push_str(" */\n");
        }
        out.push_str(&format!("export interface {name} {{\n"));
        for (fname, fschema, required) in fields(schema) {
            if let Some(d) = description(fschema) {
                out.push_str("  /**\n");
                out.push_str(&doc_lines(d, "   *", ""));
                out.push_str("   */\n");
            }
            let opt = if required { "" } else { "?" };
            out.push_str(&format!("  {fname}{opt}: {};\n", ts_type(fschema, tier)));
        }
        out.push_str("}\n\n");
    }
    out
}
