//! Emits `contracts/pipeline.json` from the crate's own types — the Rust is
//! the source of truth, the schema is a projection (decision (c),
//! `notes/DESIGN_STAGE_SDK.md`). Regenerated by the `emit-pipeline-schema`
//! binary and gated by `just check-stage-gen`; hand-editing the JSON is
//! always wrong.

use schemars::generate::SchemaSettings;
use schemars::{JsonSchema, SchemaGenerator};
use serde_json::{json, Map, Value};

use crate::events::*;
use crate::grammar_dag::GrammarDagWire;

/// One row of the event catalog: wire tag → payload schema, plus whether the
/// event carries a binary payload after the header line.
struct EventRow {
    tag: &'static str,
    schema_ref: Value,
    binary_payload: bool,
    direction: &'static str,
}

/// Build the full pipeline contract document as pretty-printed JSON.
pub fn pipeline_schema_json() -> String {
    let settings = SchemaSettings::draft2020_12().with(|s| {
        s.definitions_path = "#/components/schemas/".into();
    });
    let mut generator = SchemaGenerator::new(settings);

    let mut rows: Vec<EventRow> = Vec::new();
    {
        use crate::events::event_type as t;
        let mut row = |tag: &'static str,
                       schema_ref: Value,
                       binary_payload: bool,
                       direction: &'static str| {
            rows.push(EventRow {
                tag,
                schema_ref,
                binary_payload,
                direction,
            })
        };
        // Handshake + audio session vocabulary.
        row(
            t::CAPABILITY,
            sub::<Capability>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::AUDIO_START,
            sub::<AudioStart>(&mut generator),
            false,
            "upstream → stage",
        );
        row(
            t::AUDIO_CHUNK,
            sub::<AudioChunk>(&mut generator),
            true,
            "upstream → stage",
        );
        row(
            t::AUDIO_STOP,
            sub::<AudioStop>(&mut generator),
            false,
            "upstream → stage",
        );
        row(
            t::TRANSCRIPT,
            sub::<Transcript>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::FLOW_CREDIT,
            sub::<FlowCredit>(&mut generator),
            false,
            "stage → upstream",
        );
        row(t::ERROR, sub::<ErrorEvent>(&mut generator), false, "either");
        row(
            t::VOCABULARY_UPDATE,
            sub::<VocabularyUpdate>(&mut generator),
            false,
            "host → stage",
        );
        // Device monitoring.
        row(
            t::DEVICE_SNAPSHOT,
            sub::<DeviceSnapshot>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::DEVICE_ADDED,
            sub::<DeviceAdded>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::DEVICE_REMOVED,
            sub::<DeviceRemoved>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::DEFAULT_DEVICE_CHANGED,
            sub::<DefaultDeviceChanged>(&mut generator),
            false,
            "stage → host",
        );
        // Location.
        row(
            t::LOCATION_UPDATE,
            sub::<LocationUpdate>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::LOCATION_ERROR,
            sub::<LocationError>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::HEADING_UPDATE,
            sub::<HeadingUpdate>(&mut generator),
            false,
            "stage → host",
        );
        // Display.
        row(
            t::DISPLAY_SNAPSHOT,
            sub::<DisplaySnapshot>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::DISPLAY_ADDED,
            sub::<DisplayAdded>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::DISPLAY_REMOVED,
            sub::<DisplayRemoved>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::DISPLAY_CHANGED,
            sub::<DisplayChanged>(&mut generator),
            false,
            "stage → host",
        );
        // Power.
        row(
            t::POWER_SNAPSHOT,
            sub::<PowerSnapshot>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::POWER_SOURCE_CHANGED,
            sub::<PowerSourceChanged>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::SYSTEM_WILL_SLEEP,
            sub::<SystemSleepWake>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::SYSTEM_DID_WAKE,
            sub::<SystemSleepWake>(&mut generator),
            false,
            "stage → host",
        );
    }

    // The wire envelope and the grammar DAG root are part of the contract even
    // though no event row references the envelope.
    let header_ref = sub::<crate::wire::WireHeader>(&mut generator);
    let _ = sub::<GrammarDagWire>(&mut generator);

    let mut event_types = Map::new();
    for r in &rows {
        let mut entry = Map::new();
        entry.insert("data".to_string(), r.schema_ref.clone());
        entry.insert("direction".to_string(), json!(r.direction));
        if r.binary_payload {
            entry.insert("binary_payload".to_string(), json!(true));
        }
        event_types.insert(r.tag.to_string(), Value::Object(entry));
    }

    let definitions: Map<String, Value> = generator.take_definitions(false).into_iter().collect();

    let doc = json!({
        "$id": "https://branchkit.dev/contracts/pipeline.json",
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "description": "The BranchKit pipeline stage contract: newline-delimited JSON headers (WireHeader) with optional binary payloads, and the typed event vocabulary. GENERATED from the branchkit-stage-sdk crate by `emit-pipeline-schema` — the Rust types are the source of truth; edit them and run `just gen-stage-proto`. Drift is gated by `just check-stage-gen`.",
        "wire": {
            "framing": "One JSON object per line (the WireHeader), '\\n'-terminated, followed by exactly `payload_length` raw bytes when non-zero.",
            "header": header_ref,
            "backpressure": "Window-based flow credit: the receiver advertises an initial credit, then grants more after processing batches; the sender decrements per audio_chunk and blocks at zero. Credit sizes are receiver-chosen policy, not part of this contract."
        },
        "eventTypes": Value::Object(event_types),
        "components": { "schemas": Value::Object(definitions) }
    });
    let mut out = serde_json::to_string_pretty(&doc).expect("schema document serializes");
    out.push('\n');
    out
}

fn sub<T: JsonSchema>(generator: &mut SchemaGenerator) -> Value {
    generator.subschema_for::<T>().to_value()
}
