//! Emits `contracts/pipeline.json` from the crate's own types — the Rust is
//! the source of truth, the schema is a projection (decision (c),
//! `notes/DESIGN_STAGE_SDK.md`). Regenerated by the `emit-pipeline-schema`
//! binary and gated by `just check-stage-gen`; hand-editing the JSON is
//! always wrong.

use schemars::generate::SchemaSettings;
use schemars::{JsonSchema, SchemaGenerator};
use serde_json::{json, Map, Value};

use crate::events::*;
use crate::grammar_dag::GrammarDagWire;

/// One row of the event catalog: wire tag → payload schema, plus whether the
/// event carries a binary payload after the header line.
struct EventRow {
    tag: &'static str,
    schema_ref: Value,
    binary_payload: bool,
    direction: &'static str,
}

/// Build the full pipeline contract document as pretty-printed JSON.
pub fn pipeline_schema_json() -> String {
    let mut out =
        serde_json::to_string_pretty(&pipeline_schema_value()).expect("schema document serializes");
    out.push('\n');
    out
}

/// The contract document itself. The Go/TS emitters project from exactly this
/// value, so the ports cannot drift from the schema independently.
pub fn pipeline_schema_value() -> Value {
    let settings = SchemaSettings::draft2020_12().with(|s| {
        s.definitions_path = "#/components/schemas/".into();
    });
    let mut generator = SchemaGenerator::new(settings);

    let mut rows: Vec<EventRow> = Vec::new();
    {
        use crate::events::event_type as t;
        let mut row = |tag: &'static str,
                       schema_ref: Value,
                       binary_payload: bool,
                       direction: &'static str| {
            rows.push(EventRow {
                tag,
                schema_ref,
                binary_payload,
                direction,
            })
        };
        // Handshake + audio session vocabulary.
        row(
            t::CAPABILITY,
            sub::<Capability>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::AUDIO_START,
            sub::<AudioStart>(&mut generator),
            false,
            "upstream → stage",
        );
        row(
            t::AUDIO_CHUNK,
            sub::<AudioChunk>(&mut generator),
            true,
            "upstream → stage",
        );
        row(
            t::AUDIO_STOP,
            sub::<AudioStop>(&mut generator),
            false,
            "upstream → stage",
        );
        row(
            t::TRANSCRIPT,
            sub::<Transcript>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::FLOW_CREDIT,
            sub::<FlowCredit>(&mut generator),
            false,
            "stage → upstream",
        );
        row(t::ERROR, sub::<ErrorEvent>(&mut generator), false, "either");
        row(
            t::VOCABULARY_UPDATE,
            sub::<VocabularyUpdate>(&mut generator),
            false,
            "host → stage",
        );
        // Device monitoring.
        row(
            t::AUDIO_DEVICE_SNAPSHOT,
            sub::<AudioDeviceSnapshot>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::AUDIO_DEVICE_ADDED,
            sub::<AudioDeviceAdded>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::AUDIO_DEVICE_REMOVED,
            sub::<AudioDeviceRemoved>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::AUDIO_DEVICE_DEFAULT_CHANGED,
            sub::<AudioDeviceDefaultChanged>(&mut generator),
            false,
            "stage → host",
        );
        // Location.
        row(
            t::LOCATION_UPDATE,
            sub::<LocationUpdate>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::LOCATION_ERROR,
            sub::<LocationError>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::HEADING_UPDATE,
            sub::<HeadingUpdate>(&mut generator),
            false,
            "stage → host",
        );
        // Display.
        row(
            t::DISPLAY_SNAPSHOT,
            sub::<DisplaySnapshot>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::DISPLAY_ADDED,
            sub::<DisplayAdded>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::DISPLAY_REMOVED,
            sub::<DisplayRemoved>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::DISPLAY_CHANGED,
            sub::<DisplayChanged>(&mut generator),
            false,
            "stage → host",
        );
        // Power.
        row(
            t::POWER_SNAPSHOT,
            sub::<PowerSnapshot>(&mut generator),
            false,
            "stage → host",
        );
        row(
            t::POWER_SOURCE_CHANGED,
            sub::<PowerSourceChanged>(&mut generator),
            false,
            "stage → host",
        );
    }

    // A tag with no row regenerates contracts/pipeline.json byte-identical,
    // so `just check-stage-gen` cannot see the omission — this can.
    {
        let tagged: Vec<&str> = rows.iter().map(|r| r.tag).collect();
        let missing: Vec<&&str> = event_type::ALL
            .iter()
            .filter(|t| !tagged.contains(t))
            .collect();
        assert!(
            missing.is_empty() && tagged.len() == event_type::ALL.len(),
            "event_type::ALL and the schema row list disagree (missing rows: \
             {missing:?}) — every wire tag needs exactly one row() call here"
        );
    }

    // The wire envelope and the grammar DAG root are part of the contract even
    // though no event row references the envelope.
    let header_ref = sub::<crate::wire::WireHeader>(&mut generator);
    let _ = sub::<GrammarDagWire>(&mut generator);

    let mut event_types = Map::new();
    for r in &rows {
        let mut entry = Map::new();
        entry.insert("data".to_string(), r.schema_ref.clone());
        entry.insert("direction".to_string(), json!(r.direction));
        if r.binary_payload {
            entry.insert("binary_payload".to_string(), json!(true));
        }
        event_types.insert(r.tag.to_string(), Value::Object(entry));
    }

    let definitions: Map<String, Value> = generator.take_definitions(false).into_iter().collect();

    let doc = json!({
        "$id": "https://branchkit.dev/contracts/pipeline.json",
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "description": "The BranchKit pipeline stage contract: newline-delimited JSON headers (WireHeader) with optional binary payloads, and the typed event vocabulary. GENERATED from the branchkit-stage-sdk crate by `emit-pipeline-schema` — the Rust types are the source of truth; edit them and run `just gen-stage-proto`. Drift is gated by `just check-stage-gen`.",
        "wire": {
            "framing": "One JSON object per line (the WireHeader), '\\n'-terminated, followed by exactly `payload_length` raw bytes when non-zero.",
            "header": header_ref,
            "backpressure": "Window-based flow credit: the receiver advertises an initial credit, then grants more after processing batches; the sender decrements per audio_chunk and blocks at zero. Credit sizes are receiver-chosen policy, not part of this contract."
        },
        "eventTypes": Value::Object(event_types),
        "customEvents": {
            "namespace": format!("{}<vendor>.<name>", crate::events::EXT_EVENT_PREFIX),
            "description": "Custom-event valve for domains the typed vocabulary doesn't cover: a stage may emit event types under `ext.` with at least three non-empty dot segments (`ext.<vendor>.<name>`); the platform routes them opaquely onto its event bus with the originating stage as the source, and plugins subscribe via `consumes.events` patterns (e.g. `ext.<vendor>.*`). `data` crosses the bus; a binary payload does not (the platform forwards `payload_length` in its place — payloads stay wire-level). The namespace is reserved to stages: plugin emits of `ext.*` are rejected. Declare emitted types or an `ext.<vendor>.*` glob in Capability.emits.",
            "direction": "stage → host"
        },
        "components": { "schemas": Value::Object(definitions) }
    });
    doc
}

fn sub<T: JsonSchema>(generator: &mut SchemaGenerator) -> Value {
    generator.subschema_for::<T>().to_value()
}
